services:
  - type: web
    name: docsearch-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_APP
        value: backend.app:app
      - key: OAUTHLIB_INSECURE_TRANSPORT
        value: "0"
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_CLIENT_ID
        sync: false
      - key: FACEBOOK_CLIENT_SECRET
        sync: false
      - key: LINKEDIN_CLIENT_ID
        sync: false
      - key: LINKEDIN_CLIENT_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
